from energymonitor.scraping import chrome_browser_setup
from energymonitor.scraping import get_carbon_intensity
from energymonitor.cpu_usage import get_cpu_info
from energymonitor.co2api import get_request_co2signal