name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.8'
    - name: Install dependencies
      run: pip install -r requirements.txt

  pytest:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Run mypy
      run: mypy src/